const express = require("express");
const bodyParser = require("body-parser");

const generatorController = require("./controller/generator");

const port = process.env.PORT || 3000;

var app = express();
app.use(bodyParser.json({ limit: '200mb' }));

app.get("/", function (req, res) {
  res.status(200).send("Excel service");
  res.end("Nothing to look here, except that express works!");
});

app.post("/generateExcel", function (req, res) {
  console.log("Body", req.body);
  req.body = req.body || {};
  var name = req.body.fileName || "result.xlsx";
  var sheetName = req.body.sheetName || "Generated by mrosetti";
  const data = req.body.data;
  const buffer = generatorController.generateExcel(sheetName, data);
  res.attachment(name);
  res.end(buffer, "binary");
});

app.listen(port);
console.log(`Excel service listening at port ${port}`);
